# Generated by Django 3.0.5 on 2020-05-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200515_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='first_name',
            new_name='nome',
        ),
    ]
