# Generated by Django 3.0.5 on 2020-05-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200515_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividadevinculada',
            options={'verbose_name_plural': 'Atividades Vinculadas'},
        ),
        migrations.AlterModelOptions(
            name='disciplinaofertada',
            options={'verbose_name_plural': 'Disciplinas Ofertadas'},
        ),
        migrations.AlterModelOptions(
            name='entregaatividade',
            options={'verbose_name_plural': 'Entrega das Atividades'},
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AlterModelOptions(
            name='solicitacaomatricula',
            options={'verbose_name_plural': 'Solicitação de Matricula'},
        ),
        migrations.RenameField(
            model_name='coordenador',
            old_name='rp',
            new_name='rc',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='coordenador',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='nome',
        ),
        migrations.AddField(
            model_name='professor',
            name='rp',
            field=models.IntegerField(default=122),
            preserve_default=False,
        ),
    ]
