# Generated by Django 3.0.5 on 2020-05-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200515_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='mercado_trabalho',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
