# Generated by Django 3.0.5 on 2020-05-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_curso_mercado_trabalho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaomatricula',
            name='curso',
        ),
        migrations.AlterField(
            model_name='curso',
            name='mercado_trabalho',
            field=models.TextField(max_length=1000),
        ),
    ]
