# Generated by Django 3.0.5 on 2020-08-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200516_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadevinculada',
            name='atividade_vinculada',
            field=models.CharField(choices=[('AC1', 'AC1'), ('AC2', 'AC2'), ('AC3', 'AC3'), ('AC4', 'AC4'), ('AC5', 'AC5'), ('AC6', 'AC6'), ('AC7', 'AC7'), ('AC8', 'AC8'), ('AC9', 'AC9'), ('AC10', 'AC10')], default='AC1', max_length=4, verbose_name='Atividade Complementar'),
        ),
    ]
