# Generated by Django 3.0.5 on 2020-08-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_atividadevinculada_atividade_vinculada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'permissions': [('aluno_access', 'aluno_change')], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
    ]
