# Generated by Django 3.0.5 on 2020-08-09 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200809_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'permissions': [('aluno_access', 'alunos_change')], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
    ]
