# Generated by Django 3.0.5 on 2021-05-01 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200809_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inicio', models.DateField()),
                ('dt_fim', models.DateField()),
                ('status', models.CharField(choices=[('AV', 'Ativa'), ('CA', 'Cancelada'), ('TA', 'Trancada'), ('AE', 'Analise')], default='AE', max_length=4)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Aluno')),
                ('curso', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.Curso')),
                ('turma', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.Turma')),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
            },
        ),
    ]
