# Generated by Django 3.0.5 on 2021-05-01 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='solicitacao_matricula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.SolicitacaoMatricula'),
            preserve_default=False,
        ),
    ]
