from .aluno import Aluno
from .atividade import Atividade
from .atividade_vinculada import AtividadeVinculada
from .coordenador import Coordenador
from .curso import Curso
from .disciplina import Disciplina
from .disciplina_ofertada import DisciplinaOfertada
from .entrega_atividade import EntregaAtividade
from .matricula import Matricula
from .mensagem import Mensagem
from .professor import Professor
from .photo import Photo
from .solicitacao_matricula import SolicitacaoMatricula
from .turma import Turma